import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { GenericService } from './generic.service';

@Injectable({
  providedIn: 'root',
})
export class RelationsExternesService extends GenericService {
  constructor(private http: HttpClient) {
    super();
  }

  getDocsAdmin() {
    return [
      {
        name: 'Fiche de Proposition d’un Stage.pdf',
        url: 'assets/upload/1527157145.pdf',
      },
      {
        name: 'Lettre d’Affectation.pdf',
        url: 'assets/upload/1558706136.pdf',
      },
      {
        name: 'Modèle du Rapport du Stage.doc',
        url: 'assets/upload/1527157147.doc',
      },
      {
        name: "Lettre de liaison stage d'été.pdf",
        url: 'assets/upload/1559283976.pdf',
      },
      {
        name: 'Lettre de liaison stage volontaire.pdf',
        url: 'assets/upload/1559283978.pdf',
      },
      {
        name: 'Lettre d’affectation stage volontaire.pdf',
        url: 'assets/upload/1599477948.pdf',
      },
    ];
  }

  getDocsLicense() {
    return [
      {
        name: 'La Fiche de Proposition d’un Stage de Fin d’Etudes (SFE)',
        url: 'assets/upload/1476712981.pdf',
      },
      {
        name: 'La lettre de liaison destinée à l’entreprise (SFE)',
        url: 'assets/upload/1559283972.pdf',
      },
    ];
  }

  getDocsMastere() {
    return [
      {
        name: 'lettre Affectation MIQ',
        url: 'assets/upload/1592565488.pdf',
      },
    ];
  }

  getDocsIngenieur() {
    return [
      {
        name: 'La Fiche de Proposition d’un Stage de PFE ( Télécharger )',
        url: 'assets/upload/1440413070.pdf',
      },
      {
        name: 'La Fiche de Proposition d’un Stage de PFE ( Version Française )',
        url: 'assets/upload/1559283974.pdf',
      },
      {
        name: 'La Fiche de Proposition d’un Stage de PFE ( Version Anglaise )',
        url: 'assets/upload/1559283980.pdf',
      },
    ];
  }

  getPartenariats() {
    return [
      {
        universite: 'INSAT',
        societe: 'Onepoint Paris France',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '13 Décembre 2017',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Integration Object Tunisia',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '05 Décembre 2017',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'BOUDJEBEL VACPA',
        objet: 'Convention de recherche collaborative',
        responsable: 'Dorra Ghorbel',
        date: '29 Mai 2017',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'ODDO BHF Tunis',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '06 Novembre 2017',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'FOCUS',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '26 Septembre 2017',
        duree: '2 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Société Engineering Procurement & Project Management S.A EPPM',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '25 Septembre 2017',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Union Internationale des Banques UIB',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '14 Juillet 2017',
        duree: '2 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'TOTAL Tunisie',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '06 Janvier 2017',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Athena Technology Service (ATS)',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '2016',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Société AMC Ernest & Young (EY)',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '2016',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Réseau Ferroviaire Rapide de Tunis (RFR)',
        objet: 'Accord de partenariat',
        responsable: 'Direction INSAT',
        date: '2016',
        duree: '2 ans',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'Sortorius Stedim Bioprocess',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '2015',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'MEDIANET',
        objet: 'Mise en place d’un réseau d’affichage dynamique',
        responsable: 'Direction INSAT',
        date: '2015',
        duree: '5 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Business & Decision Tunisie',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '2015',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Société TELNET HOLDING',
        objet: 'Coopération scientifique et technique',
        responsable: 'Direction INSAT',
        date: '2015',
        duree: '3 ans',
        observation: 'Renouvable',
      },
      {
        universite: 'INSAT',
        societe: 'Agence de Promotion de l’Industrie et de l’Innovation',
        objet: 'Gogestion de la plateforme INSATinnov',
        responsable: 'Direction INSAT',
        date: '2015',
        duree: '3 ans',
        observation: 'Reconductible',
      },
      {
        universite: 'INSAT',
        societe: 'Agence Nationale de Métrologie',
        objet: 'Collaboration',
        responsable: 'Direction INSAT',
        date: '2011',
        duree: '',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'Compagnie des Phosphates de Gafsa (CPG)',
        objet: ' Gafsa (CPG)	Intervention',
        responsable: 'Direction INSAT',
        date: '2006-2010',
        duree: '',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'SOTRAPIL',
        objet: 'Collaboration',
        responsable: 'Direction INSAT',
        date: '2009',
        duree: '',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'API',
        objet: 'Mise en place de pépinières d’entreprises',
        responsable: 'Direction INSAT',
        date: '2007',
        duree: '5 ans',
        observation: 'Renouvelable',
      },
      {
        universite: 'INSAT',
        societe: 'Société des Ingrédients et Produits Alimentaires (SIPA)',
        objet: 'Coopération',
        responsable: 'Dorra Ghorbel',
        date: '2004',
        duree: '2 ans',
        observation: 'Tacite prorogation',
      },
      {
        universite: 'INSAT',
        societe: 'Société Tunisienne des Industries Alimentaires (STIAL)',
        objet: 'Contrat de formation théorique et pratique sur « La Mesure Instrumentale de la Texture »',
        responsable: 'Dorra Ghorbel',
        date: '2004',
        duree: '',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'La Tunisienne des Conserves Alimentaires (TUCAL)',
        objet: 'Contrat d’études pour le développement d’un nouveau produit',
        responsable: 'Dorra Ghorbel',
        date: '2001',
        duree: '2 ans',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'Microsoft Tunisie',
        objet: 'Protocole d’accord/Programme de formation et certification des étudiants',
        responsable: 'Direction INSAT',
        date: '2001',
        duree: '1 an',
        observation: '',
      },
      {
        universite: 'INSAT/Université Carthage',
        societe: 'Agence Universitaire de la Francophonie',
        objet: 'Hébergement du Campus Numérique Francophone',
        responsable: 'Direction INSAT',
        date: '2001',
        duree: '',
        observation: '',
      },
      {
        universite: 'INSAT',
        societe: 'Société Tunisienne du Sucre (STS)',
        objet: 'Coopération',
        responsable: 'Khaled Elloumi',
        date: '2000',
        duree: '3 ans',
        observation: 'Tacite prorogation',
      },
      {
        universite: 'INSAT',
        societe: 'Régie Nationale des Tabacs et Allumettes (RNTA)',
        objet: 'Coopération',
        responsable: '	Faouzi Ben Ammar',
        date: '2000',
        duree: '3 ans',
        observation: 'Renouvelable',
      },
    ];
  }

  getConventions() {
    return [
      {
        etablissement: 'INSAT',
        etranger: 'Palo Alto Networks California- USA',
        sujet: 'Autorized Academy Center Agreement',
        responsable: '	Adlène Loukil',
        date: 'Mars 2017',
        periode: '1 an renouvelable',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'ECOLE NATIONALE SUPERIEURE D’ELECTRICITE ET DE MECANIQUE E.N.S.E.M France-Nancy',
        sujet: 'MOBILITÉ ETUDIANTS et ENSEIGNANTS',
        responsable: 'DIRECTION INSAT',
        date: 'Mars 2017	',
        periode: '5 ANS',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'INSTITUT Français DE TUNISIE',
        sujet: 'CENTRE UNIVERSITAIRE DE DELF DE LINSAT',
        responsable: 'DIRECTION INSAT',
        date: '2016	',
        periode: '',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'ECOLE NATIONALE SUPERIEUR DE CHIMIE DE PARIS',
        sujet: 'DOUBLE DIPLÔME INTERNATIONAL',
        responsable: 'DIRECTION INSAT',
        date: '2016',
        periode: '4 ANS',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'INSTITUT BDE RECHERCHE POUR LE DEVELOPPEMENT IRD',
        sujet: 'RECHERCHE ET COOPERATION SCIENTIFIQUE',
        responsable: 'HAMDI MOKTAR',
        date: '2015',
        periode: '4 ANS',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'ECOLE DE TECHNOLOGIE SUPERIEURE QUEBEC',
        sujet: 'ACCORD CADRE UNIVERSITE',
        responsable: 'DIRECTION INSAT INSAT',
        date: '2015',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'ECOLE DE TECHNOLOGIE SUPERIEURE QUEBEC',
        sujet: 'ECHANGE CHERCHEUR ET ETUDIANTS',
        responsable: 'DIRECTION INSAT',
        date: '2010',
        periode: '5 ANS',
        observation: '',
      },
      {
        etablissement: 'INSAT /INRAP	',
        etranger: 'UNIVERITE DE VERSAILLES SAINT QUENTIN EN YVELINES',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'BEN AYED TAICIR',
        date: '2008	',
        periode: '3 ANS',
        observation: 'RENOUVABLE',
      },
      {
        etablissement: 'INSAT',
        etranger: 'SOCIETE FESTO	',
        sujet: 'CREATION CLUB MECATRONIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2005	',
        periode: '2 ANS	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'INSTITUT Français DE MECANIQUE AVANCEE',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2005	',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'INSTITUT BDE RECHERCHE POUR LE DEVELOPPEMENT IRD',
        sujet: 'RECHERCHE ET COOPERATION SCIENTIFIQUE',
        responsable: 'HAMDI MOKTAR',
        date: '2005	',
        periode: '3 ANS	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'LUND TECHNICAL INSTITUTE AT LUND UNIVERSITE SUEDE',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2004	',
        periode: '5 ANS	',
        observation: 'VOIR GARGOURI',
      },
      {
        etablissement: 'INSAT',
        etranger: 'UNIVERISITE OF HULL GRANDE BRETAGNE',
        sujet: 'RECHERCHE ET COOPERATION SCIENTIFIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2004	',
        periode: '3 ANS	',
        observation: 'VOIR MONSER LOTFI',
      },
      {
        etablissement: 'INSAT',
        etranger: 'UPPA	',
        sujet: 'ECHANGE ETUDIANTS ET CHERCHEURS',
        responsable: 'HELLAL FAYCAL',
        date: '2004	',
        periode: '',
        observation: 'AVENANT',
      },
      {
        etablissement: 'INSAT',
        etranger: 'INSA DE LYON	',
        sujet: 'COOPERATION ECHANGE DE STAGE',
        responsable: 'DIRECTION INSAT',
        date: '2003',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'ECOLE DES MINES DE DOUAI',
        sujet: 'COORDINATION TECHNIQUES ET ECHANGE SCIENTIFIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2003	',
        periode: '3 ANS	',
        observation: 'RENOUVABLE',
      },
      {
        etablissement: 'INSAT',
        etranger: 'MARSEILLE INNOVATION	',
        sujet: '	DEVELOPPEMENT DE LA CREATION ENTREPRISE',
        responsable: 'DIRECTION INSAT',
        date: '2003	',
        periode: '4 ANS	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: '	INSTITUT NATIONAL POLYTECHNIQUE TOULOUSE',
        sujet: 'FORMATION CONTINUE ET PROFESSIONNELLE',
        responsable: 'DIRECTION INSAT',
        date: '2000',
        periode: '1 AN	',
        observation: '',
      },
      {
        etablissement: 'INSAT',
        etranger: 'ECOLE CENTRALE DE LILLE',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2000	',
        periode: '4 ANS	',
        observation: '	RENOUVABLE /ANNEE',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'ECOLE NATIONALE SUPERIEUR DE CHIMIE DE PARIS',
        sujet: 'CONVENTION CADRE SCIENTIFIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2016	',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'ECOLE DE TECHNOLOGIE SUPERIEURE QUEBEC',
        sujet: 'ACCORD CADRE	',
        responsable: 'DIRECTION INSAT INSAT',
        date: '2015	',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'SAARLAND UNIVERSITY	',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'UNIVERSITE',
        date: '2015	',
        periode: '5 ANS	',
        observation: 'AVENANT',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'UNIVERSITE PAUL SABATIER-TOULOUSE III',
        sujet: 'COOERATION SCIENTIFIQUE : CHIMIE',
        responsable: 'BEN AYED TAICIR',
        date: '2011',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'UNIVERSITE AYDEN ISTANBUL',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'UNIVERSITE	',
        date: '2010	',
        periode: '3 ANS	',
        observation: '',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'UNIVERSITE DE LA ROCHELLE',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'UNIVERSITE',
        date: '2008	',
        periode: '4 ANS	',
        observation: '',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'UNIVERSITE DE PAU ET DES PAYS DE LADOUR',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'DIRECTION INSAT',
        date: '2004	',
        periode: '5 ANS	',
        observation: 'ANNEXE ECOLE DOCT CHIMIE IND',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'FACHHOCHSCHULU FUR TECHNIK UND WIRTSCHAFT BERLIN',
        sujet: 'ECHANGE DES ETUDIANTS',
        responsable: 'UNIVERSITE	',
        date: '2004	',
        periode: '5 ANS	',
        observation: 'RENOUVABLE',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'UNIVERSITE TSUKUBA JAPON',
        sujet: 'ECHANGE ENSEIGNANTS , CHERCHEURS ET ETUDIANTS',
        responsable: 'DIRECTION INSAT',
        date: '2001	',
        periode: '5 ANS	',
        observation: '',
      },
      {
        etablissement: 'UNIVERSITE DE CARTHAGE',
        etranger: 'SUPELEC',
        sujet: 'ECHANGE SCIENTIFIQUE ET PEDAGOGIQUE',
        responsable: 'UNIVERSITE	',
        date: '2001',
        periode: '3 ANS	',
        observation: 'RENOUVABLE',
      },
    ];
  }
}
